[build-system]
requires = ["scikit-build-core", "pybind11"]
build-backend = "scikit_build_core.build"

[project]
name = "bess_module"
version = "0.0.1"

[tool.scikit-build.sdist]
include = ["include/**", "src/**"]